### ISSUE TITLE
Deploying MySQL on Kubernetes - How access mysql from outside the container

### ISSUE THREAD

**Issue by eliassal** [midejoe/Install-DevOps-Tools#1]
Hi Joseph, I followed your post at https://medium.com/@midejoseph24/deploying-mysql-on-kubernetes-16758a42a746 and everything goes as expected as per your steps and I was able to access the mysql container running 
kubectl exec --stdin --tty mysql-74f8bf98c5-bl8vv -- /bin/bash
However, in the 

> Service (apiVersion: v1, kind: Service):
> it is indicated 
> ports: This section defines the ports to be exposed by the Service.
> port: 3306: Port 3306 is exposed, which corresponds to the port that MySQL uses for database connections.

This makes me understand that k8S will make connection to container available from outside.

I tried running 
`mysql -p -h 127.0.0.1 -P 3306`

but I get the following errors after entering password

> ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
> or
> ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1:3306' (111)

Is there anything missing? My understanding is that running a server inside K8S will help us work with it without the hassles of installing full VM. Thanks for your help

**Comment by midejoe** [comment]
Hi Eliassal,

I hope you're doing well, and thank you for taking the time to review my article. I'm glad to hear that the steps were helpful.

Regarding the issue you encountered while trying to connect to MySQL from outside the Kubernetes cluster using` mysql -p -h 127.0.0.1 -P 3306`, the localhost connection won't function as MySQL resides within the Kubernetes cluster.

Since you are using Minikube to access a MySQL service from outside the cluster, there are two primary options available: NodePort and LoadBalancer.

**Using a LoadBalancer**

- Minikube can emulate LoadBalancer services using minikube tunnel:

`minikube tunnel`

- Modify your MySQL Service to use LoadBalancer:

```
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: LoadBalancer
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
```
- Wait for the LoadBalancer to acquire an external IP:

`kubectl get svc mysql-service`

- Use the acquired external IP and port 3306 to connect to MySQL:

`mysql -p -h <external-ip> -P 3306`

**Using NodePort**

- Modify your MySQL Service to use NodePort:

```
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30000 # Choose a port within the NodePort range (30000-32767)
  selector:
    app: mysql
```

- Find the IP address of your Minikube instance:

`minikube ip`

Use the Minikube IP along with the chosen NodePort to access MySQL from outside the Minikube cluster:

`mysql -p -h <minikube-ip> -P <chosen-node-port>`

These options should enable access to the MySQL service from outside the Minikube cluster. Please give them a try, and if you encounter any further issues or need additional assistance, feel free to ask.
